/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.dbservice.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.rcs.dbservice.model.TwitterSettings;
import com.rcs.dbservice.service.TwitterSettingsService;
import com.rcs.dbservice.service.persistence.TweetPersistence;
import com.rcs.dbservice.service.persistence.TwitterSettingsPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the twitter settings remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rcs.dbservice.service.impl.TwitterSettingsServiceImpl}.
 * </p>
 *
 * @author rcs
 * @see com.rcs.dbservice.service.impl.TwitterSettingsServiceImpl
 * @see com.rcs.dbservice.service.TwitterSettingsServiceUtil
 * @generated
 */
public abstract class TwitterSettingsServiceBaseImpl extends BaseServiceImpl
	implements TwitterSettingsService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rcs.dbservice.service.TwitterSettingsServiceUtil} to access the twitter settings remote service.
	 */

	/**
	 * Returns the tweet local service.
	 *
	 * @return the tweet local service
	 */
	public com.rcs.dbservice.service.TweetLocalService getTweetLocalService() {
		return tweetLocalService;
	}

	/**
	 * Sets the tweet local service.
	 *
	 * @param tweetLocalService the tweet local service
	 */
	public void setTweetLocalService(
		com.rcs.dbservice.service.TweetLocalService tweetLocalService) {
		this.tweetLocalService = tweetLocalService;
	}

	/**
	 * Returns the tweet remote service.
	 *
	 * @return the tweet remote service
	 */
	public com.rcs.dbservice.service.TweetService getTweetService() {
		return tweetService;
	}

	/**
	 * Sets the tweet remote service.
	 *
	 * @param tweetService the tweet remote service
	 */
	public void setTweetService(
		com.rcs.dbservice.service.TweetService tweetService) {
		this.tweetService = tweetService;
	}

	/**
	 * Returns the tweet persistence.
	 *
	 * @return the tweet persistence
	 */
	public TweetPersistence getTweetPersistence() {
		return tweetPersistence;
	}

	/**
	 * Sets the tweet persistence.
	 *
	 * @param tweetPersistence the tweet persistence
	 */
	public void setTweetPersistence(TweetPersistence tweetPersistence) {
		this.tweetPersistence = tweetPersistence;
	}

	/**
	 * Returns the twitter settings local service.
	 *
	 * @return the twitter settings local service
	 */
	public com.rcs.dbservice.service.TwitterSettingsLocalService getTwitterSettingsLocalService() {
		return twitterSettingsLocalService;
	}

	/**
	 * Sets the twitter settings local service.
	 *
	 * @param twitterSettingsLocalService the twitter settings local service
	 */
	public void setTwitterSettingsLocalService(
		com.rcs.dbservice.service.TwitterSettingsLocalService twitterSettingsLocalService) {
		this.twitterSettingsLocalService = twitterSettingsLocalService;
	}

	/**
	 * Returns the twitter settings remote service.
	 *
	 * @return the twitter settings remote service
	 */
	public com.rcs.dbservice.service.TwitterSettingsService getTwitterSettingsService() {
		return twitterSettingsService;
	}

	/**
	 * Sets the twitter settings remote service.
	 *
	 * @param twitterSettingsService the twitter settings remote service
	 */
	public void setTwitterSettingsService(
		com.rcs.dbservice.service.TwitterSettingsService twitterSettingsService) {
		this.twitterSettingsService = twitterSettingsService;
	}

	/**
	 * Returns the twitter settings persistence.
	 *
	 * @return the twitter settings persistence
	 */
	public TwitterSettingsPersistence getTwitterSettingsPersistence() {
		return twitterSettingsPersistence;
	}

	/**
	 * Sets the twitter settings persistence.
	 *
	 * @param twitterSettingsPersistence the twitter settings persistence
	 */
	public void setTwitterSettingsPersistence(
		TwitterSettingsPersistence twitterSettingsPersistence) {
		this.twitterSettingsPersistence = twitterSettingsPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return TwitterSettings.class;
	}

	protected String getModelClassName() {
		return TwitterSettings.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = twitterSettingsPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.rcs.dbservice.service.TweetLocalService.class)
	protected com.rcs.dbservice.service.TweetLocalService tweetLocalService;
	@BeanReference(type = com.rcs.dbservice.service.TweetService.class)
	protected com.rcs.dbservice.service.TweetService tweetService;
	@BeanReference(type = TweetPersistence.class)
	protected TweetPersistence tweetPersistence;
	@BeanReference(type = com.rcs.dbservice.service.TwitterSettingsLocalService.class)
	protected com.rcs.dbservice.service.TwitterSettingsLocalService twitterSettingsLocalService;
	@BeanReference(type = com.rcs.dbservice.service.TwitterSettingsService.class)
	protected com.rcs.dbservice.service.TwitterSettingsService twitterSettingsService;
	@BeanReference(type = TwitterSettingsPersistence.class)
	protected TwitterSettingsPersistence twitterSettingsPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private TwitterSettingsServiceClpInvoker _clpInvoker = new TwitterSettingsServiceClpInvoker();
}