/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.dbService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TwitterSettings service. Represents a row in the &quot;twitter_TwitterSettings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rcs.dbService.model.impl.TwitterSettingsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rcs.dbService.model.impl.TwitterSettingsImpl}.
 * </p>
 *
 * @author rcs
 * @see TwitterSettings
 * @see com.rcs.dbService.model.impl.TwitterSettingsImpl
 * @see com.rcs.dbService.model.impl.TwitterSettingsModelImpl
 * @generated
 */
public interface TwitterSettingsModel extends AuditedModel,
	BaseModel<TwitterSettings> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a twitter settings model instance should use the {@link TwitterSettings} interface instead.
	 */

	/**
	 * Returns the primary key of this twitter settings.
	 *
	 * @return the primary key of this twitter settings
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this twitter settings.
	 *
	 * @param primaryKey the primary key of this twitter settings
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the group ID of this twitter settings.
	 *
	 * @return the group ID of this twitter settings
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this twitter settings.
	 *
	 * @param groupId the group ID of this twitter settings
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this twitter settings.
	 *
	 * @return the company ID of this twitter settings
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this twitter settings.
	 *
	 * @param companyId the company ID of this twitter settings
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this twitter settings.
	 *
	 * @return the user ID of this twitter settings
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this twitter settings.
	 *
	 * @param userId the user ID of this twitter settings
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this twitter settings.
	 *
	 * @return the user uuid of this twitter settings
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this twitter settings.
	 *
	 * @param userUuid the user uuid of this twitter settings
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this twitter settings.
	 *
	 * @return the user name of this twitter settings
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this twitter settings.
	 *
	 * @param userName the user name of this twitter settings
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this twitter settings.
	 *
	 * @return the create date of this twitter settings
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this twitter settings.
	 *
	 * @param createDate the create date of this twitter settings
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this twitter settings.
	 *
	 * @return the modified date of this twitter settings
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this twitter settings.
	 *
	 * @param modifiedDate the modified date of this twitter settings
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the application name of this twitter settings.
	 *
	 * @return the application name of this twitter settings
	 */
	@AutoEscape
	public String getApplicationName();

	/**
	 * Sets the application name of this twitter settings.
	 *
	 * @param applicationName the application name of this twitter settings
	 */
	public void setApplicationName(String applicationName);

	/**
	 * Returns the consumer key of this twitter settings.
	 *
	 * @return the consumer key of this twitter settings
	 */
	@AutoEscape
	public String getConsumerKey();

	/**
	 * Sets the consumer key of this twitter settings.
	 *
	 * @param consumerKey the consumer key of this twitter settings
	 */
	public void setConsumerKey(String consumerKey);

	/**
	 * Returns the consumer key secret of this twitter settings.
	 *
	 * @return the consumer key secret of this twitter settings
	 */
	@AutoEscape
	public String getConsumerKeySecret();

	/**
	 * Sets the consumer key secret of this twitter settings.
	 *
	 * @param consumerKeySecret the consumer key secret of this twitter settings
	 */
	public void setConsumerKeySecret(String consumerKeySecret);

	/**
	 * Returns the access token of this twitter settings.
	 *
	 * @return the access token of this twitter settings
	 */
	@AutoEscape
	public String getAccessToken();

	/**
	 * Sets the access token of this twitter settings.
	 *
	 * @param accessToken the access token of this twitter settings
	 */
	public void setAccessToken(String accessToken);

	/**
	 * Returns the access token secret of this twitter settings.
	 *
	 * @return the access token secret of this twitter settings
	 */
	@AutoEscape
	public String getAccessTokenSecret();

	/**
	 * Sets the access token secret of this twitter settings.
	 *
	 * @param accessTokenSecret the access token secret of this twitter settings
	 */
	public void setAccessTokenSecret(String accessTokenSecret);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TwitterSettings twitterSettings);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TwitterSettings> toCacheModel();

	@Override
	public TwitterSettings toEscapedModel();

	@Override
	public TwitterSettings toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}